Map<String, dynamic> mockJson() => {
      "dates": {"maximum": "2021-01-13", "minimum": "2020-12-23"},
      "page": 1,
      "results": [
        {
          "adult": false,
          "backdrop_path": "/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg",
          "genre_ids": [14, 10751, 12, 35, 27],
          "id": 531219,
          "original_language": "en",
          "original_title": "Roald Dahl's The Witches",
          "overview":
              "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
          "popularity": 1121.192,
          "poster_path": "/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
          "release_date": "2020-10-26",
          "title": "Roald Dahl's The Witches",
          "video": false,
          "vote_average": 6.9,
          "vote_count": 931
        },
        {
          "adult": false,
          "backdrop_path": "/ckfwfLkl0CkafTasoRw5FILhZAS.jpg",
          "genre_ids": [28, 35, 14],
          "id": 602211,
          "original_language": "en",
          "original_title": "Fatman",
          "overview":
              "A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
          "popularity": 1087.816,
          "poster_path": "/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg",
          "release_date": "2020-11-13",
          "title": "Fatman",
          "video": false,
          "vote_average": 5.9,
          "vote_count": 173
        },
        {
          "adult": false,
          "backdrop_path": "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
          "genre_ids": [14, 28, 12],
          "id": 464052,
          "original_language": "en",
          "original_title": "Wonder Woman 1984",
          "overview":
              "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
          "popularity": 562.298,
          "poster_path": "/di1bCAfGoJ0BzNEavLsPyxQ2AaB.jpg",
          "release_date": "2020-12-16",
          "title": "Wonder Woman 1984",
          "video": false,
          "vote_average": 8,
          "vote_count": 21
        },
        {
          "adult": false,
          "backdrop_path": "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
          "genre_ids": [12, 14, 10751, 16],
          "id": 529203,
          "original_language": "en",
          "original_title": "The Croods: A New Age",
          "overview":
              "After leaving their cave, the Croods encounter their biggest threat since leaving: another family called the Bettermans, who claim and show to be better and evolved. Grug grows suspicious of the Betterman parents, Phil and Hope,  as they secretly plan to break up his daughter Eep with her loving boyfriend Guy to ensure that their daughter Dawn has a loving and smart partner to protect her.",
          "popularity": 504.364,
          "poster_path": "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
          "release_date": "2020-11-25",
          "title": "The Croods: A New Age",
          "video": false,
          "vote_average": 7,
          "vote_count": 89
        },
        {
          "adult": false,
          "backdrop_path": "/tWxCVe4rQZa3BvR3tMT3t74oVTT.jpg",
          "genre_ids": [28, 878],
          "id": 713825,
          "original_language": "en",
          "original_title": "Robot Riot",
          "overview":
              "Unconscious soldiers are dropped into a testing site only to discover their memories have been wiped and that once docile machines are the new intelligence.",
          "popularity": 413.637,
          "poster_path": "/pXv4qbWyj6ycMaWkK2LzlizZQjf.jpg",
          "release_date": "2020-12-23",
          "title": "Robot Riot",
          "video": false,
          "vote_average": 0,
          "vote_count": 0
        },
        {
          "adult": false,
          "backdrop_path": "/wu1uilmhM4TdluKi2ytfz8gidHf.jpg",
          "genre_ids": [16, 14, 12, 35, 10751],
          "id": 400160,
          "original_language": "en",
          "original_title": "The SpongeBob Movie: Sponge on the Run",
          "overview":
              "When his best friend Gary is suddenly snatched away, SpongeBob takes Patrick on a madcap mission far beyond Bikini Bottom to save their pink-shelled pal.",
          "popularity": 407.018,
          "poster_path": "/jlJ8nDhMhCYJuzOw3f52CP1W8MW.jpg",
          "release_date": "2020-08-14",
          "title": "The SpongeBob Movie: Sponge on the Run",
          "video": false,
          "vote_average": 8,
          "vote_count": 1708
        },
        {
          "adult": false,
          "backdrop_path": "/eShw0LB5CkoEfYtpUcXPD85oz5Q.jpg",
          "genre_ids": [27, 53, 35, 14],
          "id": 551804,
          "original_language": "en",
          "original_title": "Freaky",
          "overview":
              "A mystical, ancient dagger causes a notorious serial killer to magically switch bodies with a 17-year-old girl.",
          "popularity": 396.071,
          "poster_path": "/8xC6QSyxrpm0D5A6iyHNemEWBVe.jpg",
          "release_date": "2020-11-12",
          "title": "Freaky",
          "video": false,
          "vote_average": 7.1,
          "vote_count": 176
        },
        {
          "adult": false,
          "backdrop_path": "/gkvOmVXdukAwpG8LjTaHo2l2cWU.jpg",
          "genre_ids": [27, 9648],
          "id": 571384,
          "original_language": "en",
          "original_title": "Come Play",
          "overview":
              "A lonely young boy feels different from everyone else. Desperate for a friend, he seeks solace and refuge in his ever-present cell phone and tablet. When a mysterious creature uses the boy’s devices against him to break into our world, his parents must fight to save their son from the monster beyond the screen.",
          "popularity": 199.441,
          "poster_path": "/e98dJUitAoKLwmzjQ0Yxp1VQrnU.jpg",
          "release_date": "2020-10-28",
          "title": "Come Play",
          "video": false,
          "vote_average": 6.7,
          "vote_count": 129
        },
        {
          "adult": false,
          "backdrop_path": "/jOWgFmD1H5t6nL7ChbmX8oDFUZl.jpg",
          "genre_ids": [10749, 35],
          "id": 520172,
          "original_language": "en",
          "original_title": "Happiest Season",
          "overview":
              "A young woman's plans to propose to her girlfriend while at her family's annual holiday party are upended when she discovers her partner hasn't yet come out to her conservative parents.",
          "popularity": 180.512,
          "poster_path": "/vzec9kkOSE93tygyfOktedkeOQ.jpg",
          "release_date": "2020-11-26",
          "title": "Happiest Season",
          "video": false,
          "vote_average": 7.5,
          "vote_count": 193
        },
        {
          "adult": false,
          "backdrop_path": "/jGVQ3HdSTdv6OidEhX88Z5Lpiru.jpg",
          "genre_ids": [35],
          "id": 676838,
          "original_language": "es",
          "original_title": "El Testamento de la Abuela",
          "overview":
              "When the grandmother decides that it is time to put the family affairs in order, the fights begin to inherit the house. A sequel to 'Grandma's Wedding'.",
          "popularity": 171.8,
          "poster_path": "/h1BZHYQl3pGOgaGDK6zwrOsYIop.jpg",
          "release_date": "2020-10-09",
          "title": "El Testamento de la Abuela",
          "video": false,
          "vote_average": 7.2,
          "vote_count": 16
        },
        {
          "adult": false,
          "backdrop_path": "/AdqOBPw4PdtzOcfEuQuZ8MNeTKb.jpg",
          "genre_ids": [14, 10751, 12, 18],
          "id": 413518,
          "original_language": "it",
          "original_title": "Pinocchio",
          "overview":
              "In this live-action adaptation of the beloved fairytale, old woodcarver Geppetto fashions a wooden puppet, Pinocchio, who magically comes to life. Pinocchio longs for adventure and is easily led astray, encountering magical beasts, fantastical spectacles, while making friends and foes along his journey. However, his dream is to become a real boy, which can only come true if he finally changes his ways.",
          "popularity": 150.115,
          "poster_path": "/4w1ItwCJCTtSi9nPfJC1vU6NIVg.jpg",
          "release_date": "2019-12-19",
          "title": "Pinocchio",
          "video": false,
          "vote_average": 6.7,
          "vote_count": 811
        },
        {
          "adult": false,
          "backdrop_path": "/qBxvZJoM2EJBh2eRWSYTWKZVhcd.jpg",
          "genre_ids": [27, 9648],
          "id": 595149,
          "original_language": "en",
          "original_title": "Death of Me",
          "overview":
              "A couple on holiday on a remote South Pacific island awaken one morning with a hang over and no recollection of what transpired. When playing back a video of the previous night, they see they participated in a local ritual that somehow ends with him murdering her.",
          "popularity": 106.804,
          "poster_path": "/8F9xUvb1JMWUMkFV2Yq3aiueAbq.jpg",
          "release_date": "2020-10-02",
          "title": "Death of Me",
          "video": false,
          "vote_average": 5.3,
          "vote_count": 55
        },
        {
          "adult": false,
          "backdrop_path": "/yY35sdVZtJXjeBONWH8HBXnxDgD.jpg",
          "genre_ids": [10751, 16, 35, 12, 10402, 14],
          "id": 508442,
          "original_language": "en",
          "original_title": "Soul",
          "overview":
              "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
          "popularity": 105.434,
          "poster_path": "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
          "release_date": "2020-12-25",
          "title": "Soul",
          "video": false,
          "vote_average": 0,
          "vote_count": 0
        },
        {
          "adult": false,
          "backdrop_path": "/cSpwQ1BekQ6SL8JpUDmfsCBxJDz.jpg",
          "genre_ids": [18, 53, 80],
          "id": 596161,
          "original_language": "en",
          "original_title": "Let Him Go",
          "overview":
              "Following the loss of their son, a retired sheriff and his wife leave their Montana ranch to rescue their young grandson from the clutches of a dangerous family living off the grid in the Dakotas.",
          "popularity": 92.748,
          "poster_path": "/EsLZoT8oHhQlGd1QpdbnvnwTzO.jpg",
          "release_date": "2020-11-05",
          "title": "Let Him Go",
          "video": false,
          "vote_average": 7,
          "vote_count": 54
        },
        {
          "adult": false,
          "backdrop_path": "/z8TvnEVRenMSTemxYZwLGqFofgF.jpg",
          "genre_ids": [14, 28, 12],
          "id": 458576,
          "original_language": "en",
          "original_title": "Monster Hunter",
          "overview":
              "A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
          "popularity": 90.989,
          "poster_path": "/zO9R7Z6DRDgRO9QVz4lAJg3L15o.jpg",
          "release_date": "2020-12-03",
          "title": "Monster Hunter",
          "video": false,
          "vote_average": 5.1,
          "vote_count": 17
        },
        {
          "adult": false,
          "backdrop_path": "/i923BqvEsa3OR3GntqoJR763mbg.jpg",
          "genre_ids": [53, 10749, 18],
          "id": 721625,
          "original_language": "en",
          "original_title": "Songbird",
          "overview":
              "During a pandemic lockdown, Nico, a young man with rare immunity, must overcome martial law, murderous vigilantes and a powerful family to reunite with his love, Sara.",
          "popularity": 66.803,
          "poster_path": "/a1IyqmWVZIwVGGNyoh6H2x1nbWU.jpg",
          "release_date": "2020-12-10",
          "title": "Songbird",
          "video": false,
          "vote_average": 4.6,
          "vote_count": 12
        },
        {
          "adult": false,
          "backdrop_path": "/xUUtcxWC6H48UCrpRwwSPQz69XC.jpg",
          "genre_ids": [53, 27, 28],
          "id": 659986,
          "original_language": "en",
          "original_title": "The Owners",
          "overview":
              "A group of friends think they found the perfect easy score - an empty house with a safe full of cash. But when the elderly couple that lives there comes home early, the tables are suddenly turned. As a deadly game of cat and mouse ensues, the would-be thieves must fight to save themselves from a nightmare they could never have imagined.",
          "popularity": 61.201,
          "poster_path": "/gzFatNrw0lhKD5NxaU6zC7S2KjP.jpg",
          "release_date": "2020-08-27",
          "title": "The Owners",
          "video": false,
          "vote_average": 5.7,
          "vote_count": 106
        },
        {
          "adult": false,
          "backdrop_path": "/7b5R8FfGUzlxfhOkPpL3xyIeuyF.jpg",
          "genre_ids": [18, 10402],
          "id": 502033,
          "original_language": "en",
          "original_title": "Sound of Metal",
          "overview":
              "Metal drummer Ruben begins to lose his hearing. When a doctor tells him his condition will worsen, he thinks his career and life is over. His girlfriend Lou checks the former addict into a rehab for the deaf hoping it will prevent a relapse and help him adapt to his new life. After being welcomed and accepted just as he is, Ruben must choose between his new normal and the life he once knew.",
          "popularity": 60.395,
          "poster_path": "/y89kFMNYXNKMdlZjR2yg7nQtcQH.jpg",
          "release_date": "2019-09-27",
          "title": "Sound of Metal",
          "video": false,
          "vote_average": 7.7,
          "vote_count": 89
        },
        {
          "adult": false,
          "backdrop_path": "/p9tdFuUe1Xc9YYMmPcqMczttnvG.jpg",
          "genre_ids": [16, 35, 28, 12, 10751],
          "id": 550738,
          "original_language": "fr",
          "original_title": "Spycies",
          "overview":
              "Vladimir and Hector, two secret agents opposed in every way, are trying to recover a top secret material stolen by unknown intruders.",
          "popularity": 52.4,
          "poster_path": "/jOY3dDCzjygXzumYeJ9UIyETzuj.jpg",
          "release_date": "2020-01-11",
          "title": "Spycies",
          "video": false,
          "vote_average": 7.9,
          "vote_count": 148
        },
        {
          "adult": false,
          "backdrop_path": "/e7bpDu3RKsjOYLSt9gHYT2c32Zd.jpg",
          "genre_ids": [28, 53],
          "id": 625568,
          "original_language": "en",
          "original_title": "Unhinged",
          "overview":
              "A divorced mother honks impatiently at a deranged middle-aged stranger at a red light while running late on her way to work. His road rage escalates to horrifyingly psychotic proportions as he becomes single-mindedly determined to teach her a deadly lesson for provoking him.",
          "popularity": 49.612,
          "poster_path": "/6WC3cIhuaLZSq3SbtdOp2ZTSTe.jpg",
          "release_date": "2020-07-02",
          "title": "Unhinged",
          "video": false,
          "vote_average": 6.5,
          "vote_count": 473
        }
      ],
      "total_pages": 15,
      "total_results": 282
    };
